CREATE TABLE Product (
                         id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                         name VARCHAR(255) NOT NULL
);

CREATE TABLE Seller (
                        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                        username VARCHAR(255) NOT NULL,
                        email VARCHAR(255) NOT NULL,
                        balance DECIMAL(19, 2) NOT NULL
);

CREATE TABLE Campaign (
                          id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                          campaign_name VARCHAR(255) NOT NULL,
                          keywords VARCHAR(255),
                          bid_amount DECIMAL(19, 2) NOT NULL,
                          campaign_fund DECIMAL(19, 2) NOT NULL,
                          status BOOLEAN NOT NULL,
                          town VARCHAR(255),
                          radius INT NOT NULL,
                          product_id BIGINT,
                          seller_id BIGINT,
                          FOREIGN KEY (product_id) REFERENCES Product(id),
                          FOREIGN KEY (seller_id) REFERENCES Seller(id)
);